# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currency.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='currency.proto',
  package='twirp.currency_rates',
  syntax='proto3',
  serialized_options=_b('Z\016currency_rates'),
  serialized_pb=_b('\n\x0e\x63urrency.proto\x12\x14twirp.currency_rates\"\t\n\x07Nothing\"\x16\n\x05Rates\x12\r\n\x05rates\x18\x01 \x01(\t2\\\n\rCurrencyRates\x12K\n\rGetDollarRate\x12\x1d.twirp.currency_rates.Nothing\x1a\x1b.twirp.currency_rates.RatesB\x10Z\x0e\x63urrency_ratesb\x06proto3')
)




_NOTHING = _descriptor.Descriptor(
  name='Nothing',
  full_name='twirp.currency_rates.Nothing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=49,
)


_RATES = _descriptor.Descriptor(
  name='Rates',
  full_name='twirp.currency_rates.Rates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rates', full_name='twirp.currency_rates.Rates.rates', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Nothing'] = _NOTHING
DESCRIPTOR.message_types_by_name['Rates'] = _RATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), dict(
  DESCRIPTOR = _NOTHING,
  __module__ = 'currency_pb2'
  # @@protoc_insertion_point(class_scope:twirp.currency_rates.Nothing)
  ))
_sym_db.RegisterMessage(Nothing)

Rates = _reflection.GeneratedProtocolMessageType('Rates', (_message.Message,), dict(
  DESCRIPTOR = _RATES,
  __module__ = 'currency_pb2'
  # @@protoc_insertion_point(class_scope:twirp.currency_rates.Rates)
  ))
_sym_db.RegisterMessage(Rates)


DESCRIPTOR._options = None

_CURRENCYRATES = _descriptor.ServiceDescriptor(
  name='CurrencyRates',
  full_name='twirp.currency_rates.CurrencyRates',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=75,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDollarRate',
    full_name='twirp.currency_rates.CurrencyRates.GetDollarRate',
    index=0,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_RATES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCYRATES)

DESCRIPTOR.services_by_name['CurrencyRates'] = _CURRENCYRATES

# @@protoc_insertion_point(module_scope)
